Controllers/AdminController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

using carthage.DAL;
using carthage.Models;
using carthage.Helper;

namespace carthage.Controllers;


public class AdminController : Controller
{
  public static char ishow;
  private readonly ILogger<AdminController> _logger;
  private readonly ApplicationDbContext _context;
  private readonly JwtAuthenticationManager jwtAuthenticationManager;

  public AdminController(ILogger<AdminController> logger,
  ApplicationDbContext context,
  JwtAuthenticationManager jwtAuthenticationManager)
  {
    _logger = logger;
    _context = context;
    this.jwtAuthenticationManager = jwtAuthenticationManager;
  }

  [Route("Admin/AddEvent")]
  public IActionResult Index()
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        @ViewData["user"] = user;
        @ViewData["Message"] = "-1";
        return View("/Views/Admin/addevent.cshtml");
      }
    }
    return RedirectToAction("index", "home");
  }

  public async Task<IActionResult> addEventHandle(Event ev)
  {
    var fileName = Path.GetRandomFileName()+".jpeg";
    var filePath = Path.Combine("C:/Users/wadis/Desktop/dotnet/FestivalProjectNET/wwwroot/assets/img",
            fileName);

    using (var stream = System.IO.File.Create(filePath))
    {
      await ev.image.CopyToAsync(stream);
      ev.imagePath = fileName;
    }

    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        @ViewData["user"] = user;
        try
        {
          Event? eventAddeed = _context.Events.Add(ev).Entity;
          _context.SaveChanges();
          @ViewData["Message"] = "1";
          return View("/Views/Admin/addevent.cshtml");
        }
        catch (System.Exception)
        {
          @ViewData["Message"] = "0";
          return View("/Views/Admin/addevent.cshtml");
        }
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/EventsList")]
  public IActionResult EventsList()
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        @ViewData["user"] = user;
        List<Event>? eventList = _context.Events.ToList();
        @ViewData["data"] = eventList;
        return View();
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/Event/{id:int}")]
  public IActionResult editEvent(Event ev, int id)
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        @ViewData["user"] = user;
        Event? eventToEdit = _context.Events.Where(e => e.ID == id).FirstOrDefault();
        if (eventToEdit != null)
        {
          eventToEdit.description = ev.description;
          eventToEdit.category = ev.category;
          eventToEdit.location = ev.location;
          eventToEdit.presenter = ev.presenter;
          _context.SaveChanges();
        }
        List<Event>? eventList = _context.Events.ToList();
        @ViewData["data"] = eventList;
        return View("/Views/Admin/eventsList.cshtml");
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/deleteEvent/{id:int}")]
  public IActionResult deleteEvent(int id)
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        @ViewData["user"] = user;
        Event? eventTodelete = _context.Events.Where(e => e.ID == id).FirstOrDefault();
        if (eventTodelete != null)
        {
          _context.Remove(eventTodelete);
          _context.SaveChanges();
        }
        List<Event>? eventList = _context.Events.ToList();
        @ViewData["data"] = eventList;
        return View("/Views/Admin/eventsList.cshtml");
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/Plans")]
  public IActionResult EditPlans()
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        List<Plan>? planList = _context.Plans.ToList();
        @ViewData["user"] = user;
        @ViewData["plans"] = planList;
        return View();
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/Plans/{id:int}")]
  public IActionResult EditPlansHandle(int id, EditPlan data)
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        Plan? planToEdit = _context.Plans.Where(p => p.ID == id).FirstOrDefault();
        if (planToEdit != null)
        {
          planToEdit.price = data.price;
          _context.SaveChanges();
        }
        List<Plan>? planList = _context.Plans.ToList();
        @ViewData["user"] = user;
        @ViewData["plans"] = planList;
        return View("/Views/Admin/EditPlans.cshtml");
      }
    }
    return RedirectToAction("index", "home");
  }

  [Route("Admin/OrdersList")]
  public IActionResult OrdersList()
  {
    var token = HttpContext.Session.GetString("token");
    if (token != null)
    {
      string? email = jwtAuthenticationManager.DecriptToken(token);
      User? user = _context.Users.Include(u => u.role).Where(u => u.email == email).FirstOrDefault();
      if (user != null && user.role.name == "ADMIN")
      {
        List<Order>? orders = _context.Orders.Include(u => u.ev).Include(u => u.plan).Include(u => u.user).ToList();
        @ViewData["user"] = user;
        @ViewData["orders"] = orders;
        return View("/Views/Admin/OrdersList.cshtml");
      }
    }
    return RedirectToAction("index", "home");
  }

  // AddEvent/setEventDetails
  // public IActionResult setEventDetails(EventModel e)
  // {
  //   using var connection = new MySqlConnection("Server=127.0.0.1;User ID=root;Password=;Database=festival");
  //   connection.Open();
  //   using var command = new MySqlCommand("INSERT INTO event  (EventName,EventDesc,Presenter,Category,Location)  VALUES('" + e.eventName + "','" + e.eventDesc + "','" + e.presenterName
  //   + "','" + e.category + "','" + e.location + "');", connection);

  //   try
  //   {
  //     command.ExecuteNonQuery();
  //     ishow = '1';
  //   }
  //   catch (System.Exception)
  //   {
  //     ishow = '0';
  //     return RedirectToAction("Index");
  //   }
  //   connection.Close();
  //   return RedirectToAction("Index");
  // }

  // public IActionResult dontshow()
  // {
  //   ishow = '2';
  //   return RedirectToAction("Index");
  // }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

using carthage.Models.Auth;
using carthage.Models;
using carthage.DAL;
using carthage.Helper;

namespace carthage.Controllers;

public class AuthController : Controller
{
  public static char ishow;
  private readonly ILogger<AuthController> _logger;
  private readonly ApplicationDbContext _context;
  private readonly JwtAuthenticationManager jwtAuthenticationManager;
  public AuthController(ILogger<AuthController> logger, ApplicationDbContext context, JwtAuthenticationManager jwtAuthenticationManager)
  {
    _logger = logger;
    _context = context;
    this.jwtAuthenticationManager = jwtAuthenticationManager;
  }

  [Route("Auth/signin")]
  public IActionResult SignIn()
  {
    return View("/Views/Auth/signin.cshtml");
  }


  [Route("Auth/signup")]
  public IActionResult SignUp()
  {
    return View("/Views/Auth/signup.cshtml");
  }

  [Route("Auth/signinHandle")]
  public IActionResult SignInHandle(Signin data)
  {
    string password = Crypte.EncodePasswordToBase64(data.password);
    User? user = _context.Users.Where(u => u.email == data.email && u.password == password).FirstOrDefault();
    if (user != null)
    {
      var token = jwtAuthenticationManager.Authenticate(data.email);
      HttpContext.Session.SetString("token", token);
      return RedirectToAction("index", "home");
    }
    else
    {
      @TempData["error"] = "Check your credentials";
      return RedirectToAction("signin");
    }
  }

  [Route("Auth/SignUpHandle")]
  public IActionResult SignUpHandle(SignUp data)
  {
    string password = Crypte.EncodePasswordToBase64(data.password);
    User? user = _context.Users.Where(user => user.email == data.email).FirstOrDefault();
    if (user != null)
    {
      @TempData["error"] = "Email olready exist";
      return RedirectToAction("signup");
    }
    else
    {
      Role? userRole = _context.Roles.Where(role => role.name == "USER").FirstOrDefault();
      if (userRole != null)
      {
        _context.Users.Add(new User()
        {
          email = data.email,
          password = password,
          firstName = data.firstName,
          lastName = data.lastName,
          roleID = userRole.ID
        });
        _context.SaveChanges();
        var token = jwtAuthenticationManager.Authenticate(data.email);
        HttpContext.Session.SetString("token", token);
        return RedirectToAction("index", "home");
      }
      else
      {
        @TempData["error"] = "Erreur interne";
        return RedirectToAction("signup");
      }
    }
  }

  [Route("Auth/SignOut")]
  public IActionResult SignOut()
  {
    HttpContext.Session.Remove("token");
    return RedirectToAction("index", "home");
  }


}

Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Carthage</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">
  <link href="~/assets/css/auth.css" rel="stylesheet">
</head>

<body>
  <div class="auth">
    <main id="main" class="main">
      @RenderBody()
    </main>
    <div class="auth-image">
      <img src="~/assets/img/auth.jpeg" class="image">
    </div>
  </div>
  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>

Views/Shared/_HomeLayout.cshtml
@{
  User? user = ViewData["user"] as User;
}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Carthage</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">
  <link href="~/assets/css/home.css" rel="stylesheet">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header position-absolute top-0 w-100 d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="~/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">Carthage</span>
      </a>
      <a href="/" class="header-nav-item">
        Home
      </a>
      <a href="/#about" class="header-nav-item">
        about
      </a>
      <a href="/#plans" class="header-nav-item">
        Plans
      </a>
      <a href="/Events" class="header-nav-item">
        Events
      </a>
    </div>

    <nav class="header-nav ms-auto">
      @if (user == null)
      {
        <a href="/auth/signin">
          <button class="btn btn-primary">
            Authenticate
          </button>
        </a>
      }
      else
      {
        <ul class="d-flex align-items-center">
          <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
              <span class="d-none d-md-block dropdown-toggle ps-2">@user.fullName</span>
            </a>

            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li class="dropdown-header">
                <h6>@user.fullName</h6>
              </li>
              @if (user.role.name == "ADMIN")
              {
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item d-flex align-items-center" asp-controller="Admin" asp-action="Index">
                    <i class="bi bi-person"></i>
                    <span>Dashboard</span>
                  </a>
                </li>
              }
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item d-flex align-items-center" asp-controller="Auth" asp-action="Signout">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      }
    </nav>
  </header>


  <main id="main" class="main">
    @RenderBody()
  </main>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i>
  </a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>

Views/Shared/_Layout.cshtml
@{
  User? user = ViewData["user"] as User;
}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Carthage</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="~/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">CarthageAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->



    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">@user.fullName</span>
          </a>

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>@user.fullName</h6>
            </li>
            @if (user.role.name == "ADMIN")
            {
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item d-flex align-items-center" asp-controller="Admin" asp-action="Index">
                  <i class="bi bi-person"></i>
                  <span>Dashboard</span>
                </a>
              </li>
            }
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" asp-controller="Auth" asp-action="Signout">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
          </ul>
        </li>

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="/">
          <i class="bi bi-house"></i>
          <span>Home</span>
        </a>
      </li><!-- End Home Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="/admin/AddEvent">
          <i class="bi bi-file-earmark-plus"></i>
          <span>Add Event</span>
        </a>
      </li><!-- End Add Event Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="/admin/EventsList">
          <i class="bi bi-card-checklist"></i>
          <span>Event List</span>
        </a>
      </li><!-- End Event List Nav -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="/admin/Plans">
          <i class="bi bi-tag"></i>
          <span>Plans</span>
        </a>
      </li><!-- End Plans Page Nav -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="/admin/orderslist">
          <i class="bi bi-bag"></i>
          <span>Orders</span>
        </a>
      </li><!-- End Plans Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->
  <main id="main" class="main">
    @RenderBody()
  </main>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>

Views/Shared/_TicketsLayout.cshtml
@{
  User? user = ViewData["user"] as User;
}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Carthage</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">
  <link href="~/assets/css/tickets.css" rel="stylesheet">

</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header top-0 w-100 d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="~/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">Carthage</span>
      </a>
      <a href="/" class="header-nav-item">
        Home
      </a>
      <a href="/#about" class="header-nav-item">
        about
      </a>
      <a href="/#plans" class="header-nav-item">
        Plans
      </a>
      <a href="/Events" class="header-nav-item">
        Events
      </a>
    </div>

    <nav class="header-nav ms-auto">
      @if (user == null)
      {
        <a href="/auth/signin">
          <button class="btn btn-primary">
            Authenticate
          </button>
        </a>
      }
      else
      {
        <ul class="d-flex align-items-center">
          <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
              <span class="d-none d-md-block dropdown-toggle ps-2">@user.fullName</span>
            </a>

            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li class="dropdown-header">
                <h6>@user.fullName</h6>
              </li>
              @if (user.role.name == "ADMIN")
              {
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item d-flex align-items-center" asp-controller="Admin" asp-action="Index">
                    <i class="bi bi-person"></i>
                    <span>Dashboard</span>
                  </a>
                </li>
              }
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item d-flex align-items-center" asp-controller="Auth" asp-action="Signout">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      }
    </nav>
  </header>


  <main id="main" class="main">
    @RenderBody()
  </main>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i>
  </a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.min.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>